/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package os4.serv.elements;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import os4.Common;

/**
 *
 * @author root
 */
public class ElementPanel extends javax.swing.JPanel {
    private static final Logger Log = Common.getLogger(ElementPanel.class);
    
    /**
     * Creates new form ElementPanel
     */
    public ElementPanel() {
        initComponents();
    }
    
    ActionListener Listener = null;
    public void setActionListener(ActionListener al){
        Listener = al;
    }
    
    int XStep = 1,YStep = 1;
    Font LitleFont = new Font("Serif",Font.BOLD,9);
    Font TinyFont = new Font("Serif",Font.PLAIN,9);
    Font NormalFont = new Font("Serif",Font.BOLD,12);
    @Override
    public void paintComponent(Graphics g){
        try{
            Dimension dim = getSize();
            g.setColor(Color.white);
            g.fillRect(0, 0, dim.width, dim.height);
            
            int x_step = dim.width/18; XStep = x_step;
            int y_step = dim.height/10; YStep = y_step;
            
            boolean selected;
            for (ChElement chel : ElementTable.Elements) {
                int x = x_step*(chel.Col-1);
                int y = y_step*(chel.Row-1);
                if(SelectedCol == chel.Col && SelectedRow == chel.Row)
                    selected = true;
                else
                    selected = false;
                if(selected == false)
                    g.setColor(chel.getColorForType());
                else
                    g.setColor(Color.blue);
                g.setFont(NormalFont);
                g.fillRect(x, y, x_step, y_step);
                
                if(selected == true)
                    g.setColor(Color.white);
                else
                    g.setColor(Color.black);
                g.drawRect(x, y, x_step, y_step);
                g.drawString(chel.Name, x+2, y+15);
                g.setFont(LitleFont);
                
                String str = ""+chel.AtomNum;
                FontMetrics fm = g.getFontMetrics(LitleFont);
                int w = fm.stringWidth(str);
                g.drawString(str, x+x_step-w, y+15);
                
                //g.setColor(Color.darkGray);
                g.setFont(TinyFont);
                fm = g.getFontMetrics(TinyFont);
                str = chel.FullName+" ";
                do{
                    str = str.substring(0,str.length()-1);
                    w = fm.stringWidth(str);
                } while(w > x_step);
                g.drawString(str, x+x_step-1-w, y+y_step-1);
            }
        } catch(Exception ex){
            Log.log(Level.SEVERE,"Element panel...", ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    int SelectedCol = -1;
    int SelectedRow = -1;
    public ChElement SelectedElement = null;
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        try{
            SelectedCol = evt.getX()/XStep+1;
            SelectedRow = evt.getY()/YStep+1;
            SelectedElement = null;
            for (ChElement Element : ElementTable.Elements) {
                if (Element.Col == SelectedCol && Element.Row == SelectedRow) {
                    SelectedElement = Element;
                    break;
                }
            }
            repaint();
            if(Listener != null)
                Listener.actionPerformed(null);
        }catch(Exception ex){
            Log.log(Level.SEVERE,"Elemenet table clic error",ex);
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
